### ISSUE TITLE
cannot see scrollbar in dark or streamlit themes

### ISSUE THREAD

**Issue by Travis-Barton** [PablocFonseca/streamlit-aggrid#106]
Hey all,

when I use the dark or streamlit themes, I cannot see the scrollbars. I know they're there because I can grab them blindly and move them. But I cannot see them and it makes scrolling clunky. Any idea why?

![Screenshot 2022-06-21 142147](https://user-images.githubusercontent.com/39603097/174899468-63b335c1-d352-4f16-bddb-b3b17a04436f.png)

**Comment by SergeyVolkonsky** [comment]
Hi. Same issue

**Comment by smartm13** [comment]
Firstly, I am really amazed that with very less efforts I was able to integrate this 🙌, now just looking to iron out these tiny things.
As Travis said, I also suspect that the scroll bar is still there but hardly visible. I also see others failing to change scrollbar colors. (Referring this streamlit community [comment](https://discuss.streamlit.io/t/ag-grid-component-with-input-support/8108/276))  

The real dark mode issue for me is to use the "whitewashed" sidebar for quick filtering/ordering of columns.

![image](https://user-images.githubusercontent.com/16520754/186514022-52a97cfd-5045-476f-91fb-272e5842c46e.png)

Given that this issue is open for a while, Just hoping that some CSS ninja would pass-by and save the world!!

**Comment by dectoplate** [comment]
Recently, I had to customize the scrollbar, and it might be of help in that case (of the scrollbar thumb):

    custom_css={
        # Firefox
        '*': {'scrollbar-width': 'thin;'},
        # Chrome, Edge, Opera, Safari
        '*::-webkit-scrollbar': {'width': '8px'},
        '*::-webkit-scrollbar-thumb': {
            'background-color': 'var(--ag-disabled-foreground-color)'},
    }

This CSS customization forces the scrollbar to be thin and to have exactly the same width in all browsers.
Notice that you can apply a color to the scrollbar-thumb...

(using `theme='balham'`)

**Comment by dectoplate** [comment]
Recently, I had to customize the scrollbar, and it might be of help in that case (of the scrollbar thumb):

    custom_css={
        # Firefox
        '*': {'scrollbar-width': 'thin;'},
        # Chrome, Edge, Opera, Safari
        '*::-webkit-scrollbar': {'width': '8px'},
        '*::-webkit-scrollbar-thumb': {
            'background-color': 'var(--ag-disabled-foreground-color)'},
    }

This CSS customization forces the scrollbar to be thin and to have exactly the same width in all browsers.
Notice that you can apply a color to the scrollbar thumb...

(using `theme='balham'`)
