### ISSUE TITLE
Bug: rows selected lags behind

### ISSUE THREAD

**Issue by Tauvic** [PablocFonseca/streamlit-aggrid#176]
Im working on an multi page application with tabs. I want to select multiple rows and get a list of the selected rows. When the users returns to the table I want to show the selected rows using pre_selected_rows.

But when get selected_rows it looks like the selection lags behind.
Looks to me for every selection i make table send two events, the original/old situation and the new situation.
Also it looks like the table keeps updating and looping sometimes.

Is this a bug? What is the correct way to do this? Has it to do with other incluences of multipage and tabs?
Im new to streamlit so I try now to test the most simple setup with a single page.

gb = GridOptionsBuilder.from_dataframe(df)
gb.configure_default_column(hide=True)
gb.configure_column("name",hide=False,width=300,tooltipField="name", 
                    headerCheckboxSelection=True
                    )  
gb.configure_column("branch",hide=False,width=150)        
gb.configure_column("startDate",hide=False,width=90,type=["customDateTimeFormat"])
gb.configure_column("endDate",hide=False,width=90,type=["customDateTimeFormat"])
gb.configure_column("roles",hide=False,width=300,tooltipField="roles")  
gb.configure_pagination(enabled=True,paginationPageSize=10,paginationAutoPageSize=False)
gb.configure_selection(use_checkbox=True,
                        selection_mode='multiple',
                        pre_selected_rows=selected_rows
                        )
gb.configure_grid_options(tooltipShowDelay=500)

table = AgGrid(df,
                gridOptions=gb.build(),
                enable_enterprise_modules=False,
                update_mode=GridUpdateMode.SELECTION_CHANGED
                )

selected_rows = [item['_selectedRowNodeInfo']['nodeRowIndex'] for item in table.selected_rows]
st.session_state[selected_name] = selected_rows

**Comment by bradley-hf** [comment]
I'm seeing the same problem.   The grid is always one event behind and fires multiple events

**Comment by Tauvic** [comment]
I now have added a button. When clicked i determine the selected rows and store in session state. This is a workaround for the somethwat strange behaviour. Now i can save selected rows and also show them when i switch between pages in a multipage App.
Now i see new errors in the browser log:
​ AG Grid: do not use api for selection, call node.setSelected(value) instead
t.selectIndex @ main.dc43edd4.js:2
​ AG Grid: suppressEvents is no longer supported, stop listening for the event if you no longer want it

**Comment by croots** [comment]
Hi @PablocFonseca. Thanks for your work on this excellent resource. Could we reopen this issue? It still seems to be ocuring. We're trying to build an application for a scientific publication and streamlit-aggrid seems like the best table for is (we need robust javascript compatibility and some table-table cross talk that bokeh and the native streamlit tables seem to strugle with) but we're butting up against the issue described here.

The expected behavior would be that tables retain their selection when tabs are switched.

I think the strategy of saving the response is failing because streamlit is running the code linearly when a row is selected. Since there is no callback function that runs ahead of the rest of the streamlit application, response can only be referenced after the table object is created. That means that the response variable gets overwritten _after_ it is used to update the table's data. 

<details>
  <summary>Minimally reproducible example</summary>
  `import streamlit as st
from st_aggrid import AgGrid, GridOptionsBuilder, GridUpdateMode, JsCode
import pandas as pd

df1 = pd.DataFrame({"Row1": [1, 2, 3],
                    "Row2": ["A", "B", "C"]})
df2 = pd.DataFrame({"Row1": [4, 5, 6],
                    "Row2": ["D", "E", "F"]})
df3 = pd.DataFrame({"Row1": [7, 8, 9],
                    "Row2": ["G", "H", "I"]})
df4 = pd.DataFrame({"Row1": [10, 11, 12],
                    "Row2": ["J", "K", "L"]})


t1, t2, t3, t4 = st.tabs(['Tab 1', 'Tab 2', "Tab 3", "Tab 4"])

with t1:
    st.write("This is a basic table with no key")
    builder = GridOptionsBuilder.from_dataframe(df1)
    builder.configure_selection(selection_mode='multiple', use_checkbox= True, pre_selected_rows=['0'])
    builder.configure_column("Row1", header_name="Letters")
    builder.configure_column("Row2", header_name="Numbers")
    options = builder.build()
    AgGrid(df1,
           gridOptions=options,
           )

with t2:
    st.write("This is a basic table with a key and reload_data=False")
    builder = GridOptionsBuilder.from_dataframe(df2)
    builder.configure_selection(selection_mode='multiple', use_checkbox= True, pre_selected_rows=['0'])
    builder.configure_column("Row1", header_name="Letters")
    builder.configure_column("Row2", header_name="Numbers")
    options = builder.build()
    AgGrid(df2,
           gridOptions=options,
           key="tb2",
           reload_data=False)
with t3:
    st.write("This is a basic table with a key and reload_data=True")
    builder = GridOptionsBuilder.from_dataframe(df3)
    builder.configure_selection(selection_mode='multiple', use_checkbox= True, pre_selected_rows=['0'])
    builder.configure_column("Row1", header_name="Letters")
    builder.configure_column("Row2", header_name="Numbers")
    options = builder.build()
    AgGrid(df3,
           gridOptions=options,
           key="tb3",
           reload_data=True)
with t4:
    st.write("This is a table with a manual attempt to add memory")
    builder = GridOptionsBuilder.from_dataframe(df3)
    selected_rows = st.session_state.get('tablememory', ['0'])
    builder.configure_selection(selection_mode='multiple', use_checkbox= True, pre_selected_rows=selected_rows)
    builder.configure_column("Row1", header_name="Letters")
    builder.configure_column("Row2", header_name="Numbers")
    options = builder.build()
    response = AgGrid(df3,
                gridOptions=options,
                key="tb4",
                reload_data=True,
                update_mode = GridUpdateMode.SELECTION_CHANGED)
    if response and response.get('grid_state'):
        st.session_state['tablememory'] = response.get('grid_state').get('rowSelection', [])
`
</details>
